import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { KmlGeneratedSharedModule, KasandraModellingLanguageGeneratedModule } from './generated/module';
import { KmlValidator, registerValidationChecks } from './kml-validator';
import { QualifiedNameProvider } from './kml-naming';


/**
 * Declaration of custom services - add your own service classes here.
 */
export type KmlAddedServices = {
    references: {
        QualifiedNameProvider: QualifiedNameProvider
    },
    validation: {
        KmlValidator: KmlValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type KmlServices = LangiumServices & KmlAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const KmlModule: Module<KmlServices, PartialLangiumServices & KmlAddedServices> = {
    references: {
        //ScopeComputation: (services) => new DomainModelScopeComputation(services),
        QualifiedNameProvider: () => new QualifiedNameProvider()
    },
    validation: {
        KmlValidator: () => new KmlValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createKmlServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Kml: KmlServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        KmlGeneratedSharedModule
    );
    const Kml = inject(
        createDefaultModule({ shared }),
        KasandraModellingLanguageGeneratedModule,
        KmlModule
    );
    shared.ServiceRegistry.register(Kml);
    registerValidationChecks(Kml);
    return { shared, Kml };
}
